version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hospital_user -d hospital_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://hospital_user:hospital_password@db:5432/hospital_management
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./hospital-management-backend/migrations:/app/migrations
    restart: unless-stopped

volumes:
  postgres_data: